version: '3'

services:
  app:
    image: nextcloud:latest
    container_name: nextcloud
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
    volumes:
      - /var/www/html:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: